[build]
    publish = "build/"
    command = "sed -i s@https://twitter-clone2-0-94pj.onrender.com@${https://twitter-clone2-0-94pj.onrender.com}@g netlify.toml && npm run build"
[[redirects]]
    from = "/api/*"
    to = "https://twitter-clone2-0-94pj.onrender.com/api/:splat"
    status = 200
[[redirects]]
    from = "/auth/*"
    to = "https://twitter-clone2-0-94pj.onrender.com/auth/:splat"
    status = 200
[[redirects]]
    from = "/img/*"
    to = "https://twitter-clone2-0-94pj.onrender.com/img/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200